In [14]:
import pandas as pd
df = pd.read_csv("../dataset/housing_price.csv")

In [15]:
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

5 Rows× 20 Columns

In [16]:
df["City"]

0    Hyderabad
1      Chennai
2       Mumbai
3    Bangalore
4         Pune
Name: City, dtype: object

In [17]:
df.iloc[:,[0,1,10,13,18,5,3]]

,Date,City,Distance_to_Center_km,Nearby_Malls,Property_Type,Floors,Bedrooms
0,2024-01-31,Hyderabad,10,1,Apartment,1,3
1,2024-02-29,Chennai,8,1,Apartment,1,2
2,2024-03-31,Mumbai,5,2,Villa,2,4
3,2024-04-30,Bangalore,7,1,Apartment,1,3
4,2024-05-31,Pune,9,1,Apartment,1,2

In [18]:
df.iloc[0, 1]

'Hyderabad'

In [19]:
df.loc[0, "City"]

'Hyderabad'

In [20]:
df[df["City"] == "Hyderabad"]

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available

In [21]:
df[df["Bedrooms"] > 2]

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available

In [22]:
df[df["Listing_Status"] == "Available"]

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available

In [23]:
df[df["Total_Price"] > 5000000]

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available

In [24]:
df["Price_in_Lakhs"] = df["Total_Price"] / 100000

In [25]:
df["Price_per_Sqft"] = df["Price_per_Sqft"] + 500

In [26]:
df["Luxury_Property"] = df["Total_Price"] > 8000000

In [27]:
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,Price_in_Lakhs,Luxury_Property
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,...,2,1,2.1,4700,5040000,Yes,Apartment,Available,50.4,False
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,...,2,1,2.5,5000,4500000,Yes,Apartment,Sold,45.0,False
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,...,3,2,1.8,6500,9000000,Yes,Villa,Available,90.0,True
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,...,2,1,2.0,5500,6500000,No,Apartment,Available,65.0,False
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,...,2,1,2.3,4800,4730000,Yes,Apartment,Sold,47.3,False