In [16]:
import pandas as pd

df = pd.read_csv("../dataset/housing_price.csv")

In [30]:
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,Price_Category
0,2024-01-31,HYDERABAD,1200,3,2,1,1,2015,9,4.5,...,3,2,1,2.1,4620.0,5040000,1,Apartment,Available,Standard
1,2024-02-29,CHENNAI,1000,2,2,1,1,2012,12,4.2,...,2,2,1,2.5,4950.0,4500000,1,Apartment,Sold,Standard
2,2024-03-31,MUMBAI,1500,4,3,2,2,2018,6,4.8,...,4,3,2,1.8,6600.0,9000000,1,Villa,Available,Luxury
3,2024-04-30,BANGALORE,1300,3,2,1,1,2016,8,4.6,...,3,2,1,2.0,5500.0,6500000,0,Apartment,Available,Standard
4,2024-05-31,PUNE,1100,2,2,1,1,2014,10,4.3,...,2,2,1,2.3,4730.0,4730000,1,Apartment,Sold,Standard

In [17]:
df.describe()

,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price
count,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000e+00
mean,1220.000000,2.80000,2.200000,1.200000,1.200000,2015.000000,9.000000,4.480000,7.800000,2.80000,2.200000,1.200000,2.140000,4800.000000,5.954000e+06
std,192.353841,0.83666,0.447214,0.447214,0.447214,2.236068,2.236068,0.238747,1.923538,0.83666,0.447214,0.447214,0.270185,738.241153,1.872426e+06
min,1000.000000,2.00000,2.000000,1.000000,1.000000,2012.000000,6.000000,4.200000,5.000000,2.00000,2.000000,1.000000,1.800000,4200.000000,4.500000e+06
25%,1100.000000,2.00000,2.000000,1.000000,1.000000,2014.000000,8.000000,4.300000,7.000000,2.00000,2.000000,1.000000,2.000000,4300.000000,4.730000e+06
50%,1200.000000,3.00000,2.000000,1.000000,1.000000,2015.000000,9.000000,4.500000,8.000000,3.00000,2.000000,1.000000,2.100000,4500.000000,5.040000e+06
75%,1300.000000,3.00000,2.000000,1.000000,1.000000,2016.000000,10.000000,4.600000,9.000000,3.00000,2.000000,1.000000,2.300000,5000.000000,6.500000e+06
max,1500.000000,4.00000,3.000000,2.000000,2.000000,2018.000000,12.000000,4.800000,10.000000,4.00000,3.000000,2.000000,2.500000,6000.000000,9.000000e+06

In [18]:
df["Total_Price"].mean()

np.float64(5954000.0)

In [19]:
df["Total_Price"].max()

np.int64(9000000)

In [20]:
df["Area_sqft"].min()

np.int64(1000)

In [21]:
df["Location_Rating"].mean()

np.float64(4.48)

In [22]:
df["Location_Rating"].mean()

np.float64(4.48)

In [23]:
df["City"].value_counts()

City
Hyderabad    1
Chennai      1
Mumbai       1
Bangalore    1
Pune         1
Name: count, dtype: int64

In [24]:
df.describe(include="all")

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
count,5,5,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000e+00,5,5,5
unique,5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2
top,2024-01-31,Hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Apartment,Available
freq,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3
mean,NaN,NaN,1220.000000,2.80000,2.200000,1.200000,1.200000,2015.000000,9.000000,4.480000,7.800000,2.80000,2.200000,1.200000,2.140000,4800.000000,5.954000e+06,NaN,NaN,NaN
std,NaN,NaN,192.353841,0.83666,0.447214,0.447214,0.447214,2.236068,2.236068,0.238747,1.923538,0.83666,0.447214,0.447214,0.270185,738.241153,1.872426e+06,NaN,NaN,NaN
min,NaN,NaN,1000.000000,2.00000,2.000000,1.000000,1.000000,2012.000000,6.000000,4.200000,5.000000,2.00000,2.000000,1.000000,1.800000,4200.000000,4.500000e+06,NaN,NaN,NaN
25%,NaN,NaN,1100.000000,2.00000,2.000000,1.000000,1.000000,2014.000000,8.000000,4.300000,7.000000,2.00000,2.000000,1.000000,2.000000,4300.000000,4.730000e+06,NaN,NaN,NaN
50%,NaN,NaN,1200.000000,3.00000,2.000000,1.000000,1.000000,2015.000000,9.000000,4.500000,8.000000,3.00000,2.000000,1.000000,2.100000,4500.000000,5.040000e+06,NaN,NaN,NaN
75%,NaN,NaN,1300.000000,3.00000,2.000000,1.000000,1.000000,2016.000000,10.000000,4.600000,9.000000,3.00000,2.000000,1.000000,2.300000,5000.000000,6.500000e+06,NaN,NaN,NaN
max,NaN,NaN,1500.000000,4.00000,3.000000,2.000000,2.000000,2018.000000,12.000000,4.800000,10.000000,4.00000,3.000000,2.000000,2.500000,6000.000000,9.000000e+06,NaN,NaN,NaN

In [25]:
df["Loan_Eligible"] = df["Loan_Eligible"].map({"Yes": 1, "No": 0})
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,1,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,1,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,1,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,0,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,1,Apartment,Sold

In [26]:
df["Price_per_Sqft"] = df["Price_per_Sqft"].map(lambda x: x * 1.10)
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4620.0,5040000,1,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4950.0,4500000,1,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6600.0,9000000,1,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5500.0,6500000,0,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4730.0,4730000,1,Apartment,Sold

In [27]:
df["Price_Category"] = df["Total_Price"].apply(
    lambda x: "Luxury" if x > 8000000 else "Standard"
    )
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,Price_Category
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,...,3,2,1,2.1,4620.0,5040000,1,Apartment,Available,Standard
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,...,2,2,1,2.5,4950.0,4500000,1,Apartment,Sold,Standard
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,...,4,3,2,1.8,6600.0,9000000,1,Villa,Available,Luxury
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,...,3,2,1,2.0,5500.0,6500000,0,Apartment,Available,Standard
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,...,2,2,1,2.3,4730.0,4730000,1,Apartment,Sold,Standard

In [28]:
df["City"] = df["City"].map(lambda x: x.upper())
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,Price_Category
0,2024-01-31,HYDERABAD,1200,3,2,1,1,2015,9,4.5,...,3,2,1,2.1,4620.0,5040000,1,Apartment,Available,Standard
1,2024-02-29,CHENNAI,1000,2,2,1,1,2012,12,4.2,...,2,2,1,2.5,4950.0,4500000,1,Apartment,Sold,Standard
2,2024-03-31,MUMBAI,1500,4,3,2,2,2018,6,4.8,...,4,3,2,1.8,6600.0,9000000,1,Villa,Available,Luxury
3,2024-04-30,BANGALORE,1300,3,2,1,1,2016,8,4.6,...,3,2,1,2.0,5500.0,6500000,0,Apartment,Available,Standard
4,2024-05-31,PUNE,1100,2,2,1,1,2014,10,4.3,...,2,2,1,2.3,4730.0,4730000,1,Apartment,Sold,Standard