In [5]:
import pandas as pd

df = pd.read_csv("../dataset/housing_price.csv")

In [6]:
df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [7]:
df.groupby("City")["Total_Price"].mean()

City
Bangalore    6500000.0
Chennai      4500000.0
Hyderabad    5040000.0
Mumbai       9000000.0
Pune         4730000.0
Name: Total_Price, dtype: float64

In [8]:
df.groupby("City")["Total_Price"].count()

City
Bangalore    1
Chennai      1
Hyderabad    1
Mumbai       1
Pune         1
Name: Total_Price, dtype: int64

In [9]:
df.groupby("Property_Type")["Area_sqft"].mean()

Property_Type
Apartment    1150.0
Villa        1500.0
Name: Area_sqft, dtype: float64

In [10]:
df.groupby("City")["Total_Price"].max()

City
Bangalore    6500000
Chennai      4500000
Hyderabad    5040000
Mumbai       9000000
Pune         4730000
Name: Total_Price, dtype: int64

In [11]:
df.groupby(["City", "Property_Type"])["Total_Price"].mean()

City       Property_Type
Bangalore  Apartment        6500000.0
Chennai    Apartment        4500000.0
Hyderabad  Apartment        5040000.0
Mumbai     Villa            9000000.0
Pune       Apartment        4730000.0
Name: Total_Price, dtype: float64

In [12]:
df.sort_values("Total_Price")

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available

In [13]:
df.sort_values("Total_Price", ascending=False)

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold

In [14]:
df.sort_values("City")

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [15]:
df.sort_values(["City", "Total_Price"])

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [16]:
df.sort_values("Total_Price", ascending=False).head(3)

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available