In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../dataset/housing_price.csv")

In [4]:
df.rename(columns={"Area_sqft": "Area_in_Sqft"}, inplace=True)

df.head()

,Date,City,Area_in_Sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [5]:
df.rename(columns={
    "Bedrooms": "No_of_Bedrooms",
    "Bathrooms": "No_of_Bathrooms",
    "Total_Price": "Property_Total_Price"
}, inplace=True)

df.head()

,Date,City,Area_in_Sqft,No_of_Bedrooms,No_of_Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Property_Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [6]:
df.columns = [
    "Date", "City", "Area_sqft", "Bedrooms", "Bathrooms", "Floors",
    "Parking", "Year_Built", "Property_Age", "Location_Rating",
    "Distance_to_Center_km", "Nearby_Schools", "Nearby_Hospitals",
    "Nearby_Malls", "Crime_Rate", "Price_per_Sqft", "Total_Price",
    "Loan_Eligible", "Property_Type", "Listing_Status"
]

df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [7]:
df2 = df.copy()

combined_df = pd.concat([df, df2], axis=0)

combined_df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,Yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,Yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,No,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold

In [8]:
extra_data = pd.DataFrame({
    "Agent_Name": ["Ravi", "Sita", "Arjun", "Priya", "Kiran"]
})

combined_df = pd.concat([df, extra_data], axis=1)

combined_df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,Agent_Name
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,...,3,2,1,2.1,4200,5040000,Yes,Apartment,Available,Ravi
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,...,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold,Sita
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,...,4,3,2,1.8,6000,9000000,Yes,Villa,Available,Arjun
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,...,3,2,1,2.0,5000,6500000,No,Apartment,Available,Priya
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,...,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold,Kiran

In [9]:
city_info = pd.DataFrame({
    "City": ["Hyderabad", "Chennai", "Mumbai", "Bangalore", "Pune"],
    "State": ["Telangana", "Tamil Nadu", "Maharashtra", "Karnataka", "Maharashtra"]
})

merged_df = pd.merge(df, city_info, on="City", how="left")

merged_df.head()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,...,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status,State
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,...,3,2,1,2.1,4200,5040000,Yes,Apartment,Available,Telangana
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,...,2,2,1,2.5,4500,4500000,Yes,Apartment,Sold,Tamil Nadu
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,...,4,3,2,1.8,6000,9000000,Yes,Villa,Available,Maharashtra
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,...,3,2,1,2.0,5000,6500000,No,Apartment,Available,Karnataka
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,...,2,2,1,2.3,4300,4730000,Yes,Apartment,Sold,Maharashtra