In [24]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [25]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [26]:
file_path = r"C:\Users\HARSHITHA\Downloads\price_paid_records.csv.zip"
df = pd.read_csv(file_path, compression='zip', nrows=50000)

In [27]:
print("Dataset Loaded Successfully!")
print("Shape of dataset:", df.shape)
print("\nColumns in dataset:\n", df.columns)

Dataset Loaded Successfully!
Shape of dataset: (50000, 11)

Columns in dataset:
 Index(['Transaction unique identifier', 'Price', 'Date of Transfer',
       'Property Type', 'Old/New', 'Duration', 'Town/City', 'District',
       'County', 'PPDCategory Type', 'Record Status - monthly file only'],
      dtype='object')

In [28]:
#df = df.drop(columns=[
 #   "Transaction unique identifier",
  #  "Town/City",
   # "District",
#])

#print("Columns after dropping:")
#print(df.columns)

In [29]:
df["Date of Transfer"] = pd.to_datetime(df["Date of Transfer"])

df["Year"] = df["Date of Transfer"].dt.year
df["Month"] = df["Date of Transfer"].dt.month

df = df.drop(columns=["Date of Transfer"])

df.head()

,Transaction unique identifier,Price,Property Type,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only,Year,Month
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,T,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A,1995,8
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,S,N,F,GRAYS,THURROCK,THURROCK,A,A,1995,8
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,T,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A,1995,6
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,T,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A,1995,11
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,S,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A,1995,6

In [30]:
cat_cols = ["Property Type", "Old/New", "Duration", "PPDCategory Type", "Record Status - monthly file only"]

print("Categorical columns to encode:")
print(cat_cols)

Categorical columns to encode:
['Property Type', 'Old/New', 'Duration', 'PPDCategory Type', 'Record Status - monthly file only']

In [31]:
encoder = OneHotEncoder(handle_unknown="ignore")

In [32]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", encoder, cat_cols)
    ],
    remainder="passthrough"
)

In [33]:
encoded_data = preprocessor.fit_transform(df)

print("Shape before encoding:", df.shape)
print("Shape after encoding:", encoded_data.shape)

Shape before encoding: (50000, 12)
Shape after encoding: (50000, 17)

In [34]:
encoded_feature_names = preprocessor.named_transformers_["cat"].get_feature_names_out(cat_cols)

print("Encoded categorical column names:")
print(encoded_feature_names)

Encoded categorical column names:
['Property Type_D' 'Property Type_F' 'Property Type_S' 'Property Type_T'
 'Old/New_N' 'Old/New_Y' 'Duration_F' 'Duration_L' 'PPDCategory Type_A'
 'Record Status - monthly file only_A']

In [35]:
# Combine encoded categorical column names 
# with remaining numeric columns

all_columns = list(encoded_feature_names) + \
              [col for col in df.columns if col not in cat_cols]

# Create DataFrame (NO .toarray() here)
encoded_df = pd.DataFrame(encoded_data, columns=all_columns)

# Display first 5 rows
encoded_df.head()

,Property Type_D,Property Type_F,Property Type_S,Property Type_T,Old/New_N,Old/New_Y,Duration_F,Duration_L,PPDCategory Type_A,Record Status - monthly file only_A,Transaction unique identifier,Price,Town/City,District,County,Year,Month
0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,OLDHAM,OLDHAM,GREATER MANCHESTER,1995,8
1,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,GRAYS,THURROCK,THURROCK,1995,8
2,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,HIGHBRIDGE,SEDGEMOOR,SOMERSET,1995,6
3,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,{1D861C06-A416-4865-973C-4956DB12CD12},43150,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,1995,11
4,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,WAKEFIELD,LEEDS,WEST YORKSHIRE,1995,6