In [31]:
import pandas as pd

In [32]:
df = pdf.read_csv('../dataset/dataset.csv')
df.head()

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,...,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
0,2464.0,Apartment,Residential,4.0,3.0,28900000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Dhanmondi,...,1,2,1,1,3,3,4,Dhaka,Dhanmondi,11728.896104
1,1920.0,Apartment,Residential,3.0,3.0,20000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Bashundhara R-A,...,1,1,2,1,3,2,3,Dhaka,Bashundhara R/A,10416.666667
2,1445.0,Apartment,Residential,3.0,3.0,10800000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Banasree,...,1,2,2,1,1,3,4,Dhaka,Khilgaon,7474.048443
3,1475.0,Apartment,Residential,3.0,3.0,10500000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Uttara,...,1,2,3,1,3,3,4,Dhaka,Uttara,7118.644068
4,1066.0,Apartment,Residential,2.0,3.0,8000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Sutrapur,...,1,1,2,1,4,3,4,Dhaka,Sutrapur,7504.690432

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe=OneHotEncoder(handle_unknown="ignore", sparse_output=False).set_output(transform="pandas")

In [35]:
ohe_transformed = ohe.fit_transform(df[['building_type']])
ohe_transformed

,building_type_Apartment,building_type_Building,building_type_Duplex,building_type_House,building_type_Office,building_type_Others,building_type_Shop
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
18749,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18750,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18751,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18752,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18753,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [36]:
df = pd.concat([df.drop(columns=['building_type']), ohe_transformed], axis=1)

In [37]:
df

,area,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,address,...,division,zone,price_per_sqft,building_type_Apartment,building_type_Building,building_type_Duplex,building_type_House,building_type_Office,building_type_Others,building_type_Shop
0,2464.0,Residential,4.0,3.0,28900000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Dhanmondi,Unknown,...,Dhaka,Dhanmondi,11728.896104,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1920.0,Residential,3.0,3.0,20000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Bashundhara R-A,Block J,...,Dhaka,Bashundhara R/A,10416.666667,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1445.0,Residential,3.0,3.0,10800000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Banasree,"Block M, South Banasree Project",...,Dhaka,Khilgaon,7474.048443,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1475.0,Residential,3.0,3.0,10500000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Uttara,Sector 10,...,Dhaka,Uttara,7118.644068,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1066.0,Residential,2.0,3.0,8000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Sutrapur,Narinda,...,Dhaka,Sutrapur,7504.690432,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,JC...",...,Dhaka,Bashundhara R/A,9600.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18750,375.0,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,:J...",...,Dhaka,Bashundhara R/A,9600.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18751,800.0,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,JC...",...,Dhaka,Bashundhara R/A,6000.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18752,800.0,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,Dhaka",...,Dhaka,Bashundhara R/A,6000.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18753,1600.0,Commercial,3.0,3.0,2850000.0,https://www.thetolet.com/en/dhaka/adabor/31021...,Rent,Dhaka,Adabor,"7,88,Adabor,Dhaka,7,88,Adabor,Dhaka,বাসা ৮৮,রো...",...,Dhaka,Mohammadpur,1781.250000,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [38]:
from sklearn.preprocessing import OrdinalEncoder

In [39]:
df['size_category'] = pd.cut(
    df['area'],
    bins=[0, 1200, 2500, df['area'].max()],
    labels=['Small', 'Medium', 'Large']
)

In [ ]:
oe = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])
df['size_encoded'] = oe.fit_transform(df[['size_category']])
df[['area', 'size_category', 'size_encoded']].head()

In [42]:
size = ['Small', 'Medium', 'Large']
oe = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])
df['size_encoded'] = oe.fit_transform(df[['size_category']])

In [46]:
df[['area', 'size_category', 'size_encoded']].drop(columns=['area'])

      size_category  size_encoded
0            Medium           1.0
1            Medium           1.0
2            Medium           1.0
3            Medium           1.0
4             Small           0.0
...             ...           ...
18749         Small           0.0
18750         Small           0.0
18751         Small           0.0
18752         Small           0.0
18753        Medium           1.0

[18754 rows x 2 columns]

In [47]:
df['size_category'] = enc.fit_transform(df[['size_category']])

In [48]:
df

,area,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,address,...,price_per_sqft,building_type_Apartment,building_type_Building,building_type_Duplex,building_type_House,building_type_Office,building_type_Others,building_type_Shop,size_category,size_encoded
0,2464.0,Residential,4.0,3.0,28900000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Dhanmondi,Unknown,...,11728.896104,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,1920.0,Residential,3.0,3.0,20000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Bashundhara R-A,Block J,...,10416.666667,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
2,1445.0,Residential,3.0,3.0,10800000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Banasree,"Block M, South Banasree Project",...,7474.048443,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,1475.0,Residential,3.0,3.0,10500000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Uttara,Sector 10,...,7118.644068,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4,1066.0,Residential,2.0,3.0,8000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Sutrapur,Narinda,...,7504.690432,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,JC...",...,9600.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18750,375.0,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,:J...",...,9600.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18751,800.0,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,JC...",...,6000.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18752,800.0,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,"Bashundhara R.A,Dhaka,Bashundhara R.A,Dhaka,Dhaka",...,6000.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18753,1600.0,Commercial,3.0,3.0,2850000.0,https://www.thetolet.com/en/dhaka/adabor/31021...,Rent,Dhaka,Adabor,"7,88,Adabor,Dhaka,7,88,Adabor,Dhaka,বাসা ৮৮,রো...",...,1781.250000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0

In [54]:
freq_encoding = df['building_nature'].value_counts()
df['building_nature_frq'] = df['building_nature'].map(freq_encoding)
df = df[['building_nature', 'building_nature_frq']]

In [55]:
df

      building_nature  building_nature_frq
0         Residential                17926
1         Residential                17926
2         Residential                17926
3         Residential                17926
4         Residential                17926
...               ...                  ...
18749     Residential                17926
18750     Residential                17926
18751     Residential                17926
18752     Residential                17926
18753      Commercial                  828

[18754 rows x 2 columns]