In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('/home/sukesh/Desktop/RealtyAI/B-13-RealtyAI-Smart-Real-Estate-Insight-Platform/dataset/price_paid_records.csv')

In [2]:
df

,Transaction unique identifier,Price,Date of Transfer,Property Type,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,T,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,S,N,F,GRAYS,THURROCK,THURROCK,A,A
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,T,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,T,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,S,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A
...,...,...,...,...,...,...,...,...,...,...,...
22489343,{4C4EE000-291A-1854-E050-A8C063054F34},175000,2017-02-20 00:00,S,N,F,LEEDS,LEEDS,WEST YORKSHIRE,A,A
22489344,{4C4EE000-291B-1854-E050-A8C063054F34},586945,2017-02-15 00:00,D,N,F,WETHERBY,LEEDS,WEST YORKSHIRE,A,A
22489345,{4C4EE000-291C-1854-E050-A8C063054F34},274000,2017-02-24 00:00,D,N,L,HUDDERSFIELD,KIRKLEES,WEST YORKSHIRE,A,A
22489346,{4C4EE000-291D-1854-E050-A8C063054F34},36000,2017-02-22 00:00,T,N,F,HALIFAX,CALDERDALE,WEST YORKSHIRE,A,A
22489347,{4C4EE000-291E-1854-E050-A8C063054F34},145000,2017-03-03 00:00,T,N,F,LEEDS,LEEDS,WEST YORKSHIRE,A,A

In [3]:
df.head()

,Transaction unique identifier,Price,Date of Transfer,Property Type,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,T,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,S,N,F,GRAYS,THURROCK,THURROCK,A,A
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,T,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,T,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,S,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A

In [4]:
df.shape

(22489348, 11)

In [5]:
df.columns

Index(['Transaction unique identifier', 'Price', 'Date of Transfer',
       'Property Type', 'Old/New', 'Duration', 'Town/City', 'District',
       'County', 'PPDCategory Type', 'Record Status - monthly file only'],
      dtype='str')

In [6]:
df.dtypes

Transaction unique identifier          str
Price                                int64
Date of Transfer                       str
Property Type                          str
Old/New                                str
Duration                               str
Town/City                              str
District                               str
County                                 str
PPDCategory Type                       str
Record Status - monthly file only      str
dtype: object

In [7]:
df.describe()

              Price
count  2.248935e+07
mean   1.782442e+05
std    3.903677e+05
min    1.000000e+00
25%    7.500000e+04
50%    1.300000e+05
75%    2.100000e+05
max    9.890000e+07

In [8]:
highest_price_record = df.loc[df["Price"].idxmax()]
print(highest_price_record)

Transaction unique identifier        {50F18103-E682-9FD5-E050-A8C063054923}
Price                                                              98900000
Date of Transfer                                           2016-11-24 00:00
Property Type                                                             O
Old/New                                                                   N
Duration                                                                  F
Town/City                                                            LONDON
District                                                CITY OF WESTMINSTER
County                                                       GREATER LONDON
PPDCategory Type                                                          B
Record Status - monthly file only                                         A
Name: 21906462, dtype: object

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(22489348, 11)

In [11]:
df_encoded = pd.get_dummies(df, columns=["Property Type"])

In [12]:
df_encoded.head()

,Transaction unique identifier,Price,Date of Transfer,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only,Property Type_D,Property Type_F,Property Type_O,Property Type_S,Property Type_T
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A,False,False,False,False,True
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,N,F,GRAYS,THURROCK,THURROCK,A,A,False,False,False,True,False
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A,False,False,False,False,True
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A,False,False,False,False,True
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A,False,False,False,True,False

In [13]:
df_encoded = pd.get_dummies(df, columns=["Property Type"], dtype=int)

In [14]:
df_encoded.head()

,Transaction unique identifier,Price,Date of Transfer,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only,Property Type_D,Property Type_F,Property Type_O,Property Type_S,Property Type_T
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A,0,0,0,0,1
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,N,F,GRAYS,THURROCK,THURROCK,A,A,0,0,0,1,0
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A,0,0,0,0,1
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A,0,0,0,0,1
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A,0,0,0,1,0

In [15]:
df = pd.get_dummies(df, columns=["Property Type"], dtype=int)

In [16]:
df.shape

(22489348, 15)

In [17]:
df.head()

,Transaction unique identifier,Price,Date of Transfer,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only,Property Type_D,Property Type_F,Property Type_O,Property Type_S,Property Type_T
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A,0,0,0,0,1
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,N,F,GRAYS,THURROCK,THURROCK,A,A,0,0,0,1,0
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A,0,0,0,0,1
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A,0,0,0,0,1
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A,0,0,0,1,0

In [18]:
df["Old/New"].unique()

<StringArray>
['N', 'Y']
Length: 2, dtype: str

In [19]:
df["PPDCategory Type"].unique()

<StringArray>
['A', 'B']
Length: 2, dtype: str

In [20]:
df["Duration"].unique()

<StringArray>
['F', 'L', 'U']
Length: 3, dtype: str

In [21]:
df["Record Status - monthly file only"].unique()

<StringArray>
['A']
Length: 1, dtype: str

In [22]:
df["Town/City"].unique()

<StringArray>
[          'OLDHAM',            'GRAYS',       'HIGHBRIDGE',
          'BEDFORD',        'WAKEFIELD',        'SALISBURY',
           'WITNEY',      'ST. AUSTELL',        'GREENFORD',
         'FERNDALE',
 ...
 'LLANNERCH-Y-MEDD',          'ST BEES',          'MINDRUM',
 'HINTON ST GEORGE',    'PORT DINORWIC',           'GRETNA',
            'KELSO',        'THORNHILL',     'BILLINGHURST',
          'GATWICK']
Length: 1170, dtype: str

In [23]:
df["Old/New"] = df["Old/New"].map({
    "Y": 0,   
    "N": 1    
})

In [24]:
df["Old/New"].dtype

dtype('int64')

In [25]:
df = pd.get_dummies(df, columns=["Duration"], dtype=int)

In [26]:
df["PPDCategory Type"] = df["PPDCategory Type"].map({
    "A": 0,
    "B": 1
})

In [27]:
df.drop("Transaction unique identifier", axis=1, inplace=True)

In [28]:
print(df.isnull().sum())

Price                                0
Date of Transfer                     0
Old/New                              0
Town/City                            0
District                             0
County                               0
PPDCategory Type                     0
Record Status - monthly file only    0
Property Type_D                      0
Property Type_F                      0
Property Type_O                      0
Property Type_S                      0
Property Type_T                      0
Duration_F                           0
Duration_L                           0
Duration_U                           0
dtype: int64

In [29]:
df["Date of Transfer"] = pd.to_datetime(df["Date of Transfer"])

df["Year"] = df["Date of Transfer"].dt.year
df["Month"] = df["Date of Transfer"].dt.month

df.drop("Date of Transfer", axis=1, inplace=True)

In [30]:
df.head()

,Price,Old/New,Town/City,District,County,PPDCategory Type,Record Status - monthly file only,Property Type_D,Property Type_F,Property Type_O,Property Type_S,Property Type_T,Duration_F,Duration_L,Duration_U,Year,Month
0,25000,1,OLDHAM,OLDHAM,GREATER MANCHESTER,0,A,0,0,0,0,1,1,0,0,1995,8
1,42500,1,GRAYS,THURROCK,THURROCK,0,A,0,0,0,1,0,1,0,0,1995,8
2,45000,1,HIGHBRIDGE,SEDGEMOOR,SOMERSET,0,A,0,0,0,0,1,1,0,0,1995,6
3,43150,1,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,0,A,0,0,0,0,1,1,0,0,1995,11
4,18899,1,WAKEFIELD,LEEDS,WEST YORKSHIRE,0,A,0,0,0,1,0,1,0,0,1995,6

In [31]:
df = df[df["Price"] > 0]

In [32]:
print(df["Price"].skew())

91.49926338777564

In [33]:

df["Price"] = np.log1p(df["Price"])

In [34]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first', sparse_output=False)

In [35]:
df["District"].unique()

<StringArray>
[                   'OLDHAM',                  'THURROCK',
                 'SEDGEMOOR',        'NORTH BEDFORDSHIRE',
                     'LEEDS',                 'SALISBURY',
          'WEST OXFORDSHIRE',                 'RESTORMEL',
                    'EALING',                   'RHONDDA',
 ...
 'CHESHIRE WEST AND CHESTER',             'CARDIGANSHIRE',
     'BLACKBURN WITH DARWEN',             'CHESHIRE EAST',
                    'WREKIN',             'CITY OF DERBY',
                    'RADNOR',                    'BRYHER',
           'ISLES OF SCILLY',               'ST MARTIN'S']
Length: 454, dtype: str

In [36]:
df.to_csv("my_dataset.csv", index=False)

# RealtyAI — Notebook Walkthrough

## Overview
This notebook loads a UK property price dataset, inspects and cleans it, and applies basic categorical encoding to prepare data for analysis or modeling.

## Cells / Steps (summary)
- Cell 0: import pandas; read CSV into `df`.
- Cells 1–6: quick inspections — display `df`, `df.head()`, `df.shape`, `df.columns`, `df.dtypes`, `df.describe()`.
- Cell 7: identify highest-price record via `df.loc[df["Price"].idxmax()]`.
- Cells 8–9: remove duplicates (`df = df.drop_duplicates()`) and re-check shape.
- Cells 10–16: create one-hot encodings for `Property Type` (using `pd.get_dummies`), show head and update `df`.
- Cells 17–21: inspect unique values for `Old/New`, `PPDCategory Type`, `Duration`, `Record Status - monthly file only`, `Town/City`.
- Cell 22: map `Old/New` to numeric (Y→0, N→1).
- Cell 23: check dtype of `Old/New`.
- Cell 24: one-hot encode `Duration`.
- Cell 25: map `PPDCategory Type` (A→0, B→1).


## Current key variables
- `df` (pandas.DataFrame): cleaned dataset with encoded categorical columns; 17 columns after operations.
- `df_encoded` (pandas.DataFrame): alternative encoding view; 15 columns.

# 📊 Final Encoding Strategy Used in Dataset

This document explains which encoding technique was applied to each column and why it was chosen.

---

# ✅ Final Dataset Columns After Encoding

Transaction unique identifier  
Price  
Date of Transfer  
Old/New  
Town/City  
District  
County  
PPDCategory Type  
Record Status  
Property Type_D  
Property Type_F  
Property Type_O  
Property Type_S  
Property Type_T  
Duration_F  
Duration_L  
Duration_U  

---

# 📋 Encoding Decisions

| Column | Encoding Used | Why This Encoding Was Used |
|----------|---------------|----------------------------|
| Property Type | One-Hot Encoding | Nominal categorical, no natural order |
| Duration | One-Hot Encoding | Nominal categorical, no ranking between F, L, U |
| Old/New | Binary Encoding (0/1) | Only two values, efficient and logical |
| PPDCategory Type | Binary Encoding (0/1) | Two categories, memory efficient |
| Record Status | Not encoded (Filtered or kept as metadata) | Not a predictive feature |
| Town/City | Not encoded yet (requires advanced encoding) | High-cardinality feature |
| District | Not encoded yet (requires advanced encoding) | High-cardinality feature |
| County | Not encoded yet (frequency/one-hot optional) | Medium-cardinality feature |
| Transaction ID | Not encoded | Unique identifier, not predictive |

---

# 🔹 1️⃣ Property Type → One-Hot Encoding

Original values:
D, S, T, F, O

Converted into:

Property Type_D  
Property Type_S  
Property Type_T  
Property Type_F  
Property Type_O  

### Why?

- No logical ranking exists between property structures.
- Prevents artificial ordering.
- Makes each category independent.

---

# 🔹 2️⃣ Duration → One-Hot Encoding

Original values:
F (Freehold), L (Leasehold), U (Unknown)

Converted into:

Duration_F  
Duration_L  
Duration_U  

### Why?

- No natural order between ownership types.
- One-hot prevents incorrect numeric relationships.

---

# 🔹 3️⃣ Old/New → Binary Encoding

Mapped as:

Y → 0  
N → 1  

### Why?

- Only two categories.
- Efficient for ML models.
- Saves memory compared to one-hot.

---

# 🔹 4️⃣ PPDCategory Type → Binary Encoding

Mapped as:

A → 0  
B → 1  

### Why Not One-Hot?

Even though it has two categories:

- Binary mapping is more memory efficient.
- No need to create two separate columns.
- Keeps model simple.

Important Principle:

👉 Number of categories does NOT decide encoding type.  
👉 Feature meaning decides encoding.

---

# 🔹 5️⃣ Record Status

Values:
A (Added), C (Changed)

### Why Not Encoded?

- Represents dataset maintenance information.
- Not related to property characteristics.
- Usually filtered or dropped in ML models.

---

# 🔹 6️⃣ Location Columns (Town/City, District, County)

Currently not encoded in this version.

Reason:

- High-cardinality features.
- One-hot encoding would create too many columns.
- Should use Target Encoding or Frequency Encoding for ML projects.

---

# 🎯 Final Machine Learning Principles Applied

✔ Nominal categorical → One-Hot Encoding  
✔ Binary categorical → Map to 0/1  
✔ Metadata columns → Remove or filter  
✔ Unique identifiers → Drop before modeling  
✔ Encoding choice depends on feature meaning, not number of categories  




Data Cleaning & Preprocessing Report
✅ 1️⃣ Drop Unnecessary Columns

The following columns were removed as they do not contribute to price prediction:

❌ Transaction unique identifier (irrelevant ID column)

❌ Record Status - monthly file only (administrative metadata)

❌ Any constant column (no variance, no predictive value)

Reason:
These columns do not influence the target variable (Price) and may introduce noise.

✅ 2️⃣ Handle Missing Values

Missing values were checked using:

df.isnull().sum()

Result:

All columns contained 0 missing values.

Conclusion:
No imputation or row removal was required.

✅ 3️⃣ Remove Impossible Values

To ensure data integrity, invalid price values were removed:

df = df[df["Price"] > 0]

Reason:

Price ≤ 0 is logically invalid for property transactions.

Only realistic property values were retained.

No aggressive outlier deletion was performed.

✅ 4️⃣ Handle Skewness

Initial skewness of Price:

df["Price"].skew()

Result:

Skewness ≈ 91 (extremely right-skewed)

To correct this, log transformation was applied:

import numpy as np
df["Price"] = np.log1p(df["Price"])

After transformation:

Skewness ≈ 0

Distribution became approximately symmetric.

Reason:
House prices typically follow a right-skewed distribution due to high-value luxury properties.
Log transformation stabilizes variance and reduces the influence of extreme values.