In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/HP/Downloads/archive (1)/House Price India.csv", index_col=0)

In [3]:
df.head()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
id,,,,,,,,,,,,,,,,,,,,,
6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,8,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,8,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,9,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,8,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,9,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [4]:
df.tail()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
id,,,,,,,,,,,,,,,,,,,,,
6762830250,42734,2,1.5,1556,20000,1.0,0,0,4,7,...,1957,0,122066,52.6191,-114.472,2250,17286,3,76,221700
6762830339,42734,3,2.0,1680,7000,1.5,0,0,4,7,...,1968,0,122072,52.5075,-114.393,1540,7480,3,59,219200
6762830618,42734,2,1.0,1070,6120,1.0,0,0,3,6,...,1962,0,122056,52.7289,-114.507,1130,6120,2,64,209000
6762830709,42734,4,1.0,1030,6621,1.0,0,0,4,6,...,1955,0,122042,52.7157,-114.411,1420,6631,3,54,205000
6762831463,42734,3,1.0,900,4770,1.0,0,0,3,6,...,1969,2009,122018,52.5338,-114.552,900,3480,2,55,146000

In [5]:
df.describe()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,14619.000000,14619.000000,14619.000000,14619.000000,1.461900e+04,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,...,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,1.461900e+04
mean,42604.546412,3.379233,2.129557,2098.156851,1.509369e+04,1.502326,0.007661,0.232848,3.430399,7.682263,...,1970.929817,90.930228,122033.064300,52.792843,-114.403996,1996.641836,12754.003078,2.012244,64.951433,5.388063e+05
std,67.343747,0.938655,0.769955,928.218740,3.792089e+04,0.540241,0.087196,0.765651,0.664047,1.174917,...,29.491743,416.230218,19.081451,0.137525,0.141325,691.078387,26059.234785,0.817312,8.936129,3.672294e+05
min,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,4.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,42546.000000,3.000000,1.750000,1440.000000,5.010500e+03,1.000000,0.000000,0.000000,3.000000,7.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.500000,1.000000,57.000000,3.200000e+05
50%,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,8.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,13.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14619 entries, 6762810635 to 6762831463
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Date                                   14619 non-null  int64
 1   number of bedrooms                     14619 non-null  int64
 2   number of bathrooms                    14619 non-null  float64
 3   living area                            14619 non-null  int64
 4   lot area                               14619 non-null  int64
 5   number of floors                       14619 non-null  float64
 6   waterfront present                     14619 non-null  int64
 7   number of views                        14619 non-null  int64
 8   condition of the house                 14619 non-null  int64
 9   grade of the house                     14619 non-null  int64
 10  Area of the house(excluding basement)  14619 non-null  int64
 11  Area of the basement                   14619 non-null  int64
 12  Built Year                             14619 non-null  int64
 13  Renovation Year                        14619 non-null  int64
 14  Postal Code                            14619 non-null  int64
 15  Lattitude                              14619 non-null  float64
 16  Longitude                              14619 non-null  float64
 17  living_area_renov                      14619 non-null  int64
 18  lot_area_renov                         14619 non-null  int64
 19  Number of schools nearby               14619 non-null  int64
 20  Distance from the airport              14619 non-null  int64
 21  Price                                  14619 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 2.6 MB

In [7]:
# Numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("Numerical columns:")
print(numerical_cols)

print("\nCategorical columns:")
print(categorical_cols)

Numerical columns:
Index(['Date', 'number of bedrooms', 'number of bathrooms', 'living area',
       'lot area', 'number of floors', 'waterfront present', 'number of views',
       'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

Categorical columns:
Index([], dtype='object')

In [8]:
categorical_cols = [
    'Postal Code',
    'waterfront present',
    'condition of the house',
    'grade of the house',
    'number of floors',
    'number of views'
]

numerical_cols = [
    'number of bedrooms',
    'number of bathrooms',
    'living area',
    'lot area',
    'Area of the house(excluding basement)',
    'Area of the basement',
    'Built Year',
    'Renovation Year',
    'Lattitude',
    'Longitude',
    'living_area_renov',
    'lot_area_renov',
    'Number of schools nearby',
    'Distance from the airport'
]

print("Categorical:", categorical_cols)
print("Numerical:", numerical_cols)

Categorical: ['Postal Code', 'waterfront present', 'condition of the house', 'grade of the house', 'number of floors', 'number of views']
Numerical: ['number of bedrooms', 'number of bathrooms', 'living area', 'lot area', 'Area of the house(excluding basement)', 'Area of the basement', 'Built Year', 'Renovation Year', 'Lattitude', 'Longitude', 'living_area_renov', 'lot_area_renov', 'Number of schools nearby', 'Distance from the airport']

In [6]:
print(df.index.name)

id

In [7]:
df.reset_index(inplace=True)

In [8]:
df.drop('id', axis=1, inplace=True)

In [9]:
df.head()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,42491,4,2.50,2920,4000,1.5,0,0,5,8,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,42491,5,2.75,2910,9480,1.5,0,0,3,8,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,42491,4,2.50,3310,42998,2.0,0,0,3,9,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,42491,3,2.00,2710,4500,1.5,0,0,4,8,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,42491,3,2.50,2600,4750,1.0,0,0,4,9,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [10]:
df['Date'] = pd.to_datetime(df['Date'], unit='D', origin='1970-01-01')

df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month

df.drop('Date', axis=1, inplace=True)

In [11]:
df = pd.get_dummies(df, columns=['Postal Code'], drop_first=True)

In [12]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 91 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   number of bedrooms                     14619 non-null  int64
 1   number of bathrooms                    14619 non-null  float64
 2   living area                            14619 non-null  int64
 3   lot area                               14619 non-null  int64
 4   number of floors                       14619 non-null  float64
 5   waterfront present                     14619 non-null  int64
 6   number of views                        14619 non-null  int64
 7   condition of the house                 14619 non-null  int64
 8   grade of the house                     14619 non-null  int64
 9   Area of the house(excluding basement)  14619 non-null  int64
 10  Area of the basement                   14619 non-null  int64
 11  Built Year                             14619 non-null  int64
 12  Renovation Year                        14619 non-null  int64
 13  Lattitude                              14619 non-null  float64
 14  Longitude                              14619 non-null  float64
 15  living_area_renov                      14619 non-null  int64
 16  lot_area_renov                         14619 non-null  int64
 17  Number of schools nearby               14619 non-null  int64
 18  Distance from the airport              14619 non-null  int64
 19  Price                                  14619 non-null  int64
 20  year                                   14619 non-null  int32
 21  month                                  14619 non-null  int32
 22  Postal Code_122004                     14619 non-null  bool
 23  Postal Code_122005                     14619 non-null  bool
 24  Postal Code_122006                     14619 non-null  bool
 25  Postal Code_122007                     14619 non-null  bool
 26  Postal Code_122008                     14619 non-null  bool
 27  Postal Code_122009                     14619 non-null  bool
 28  Postal Code_122010                     14619 non-null  bool
 29  Postal Code_122011                     14619 non-null  bool
 30  Postal Code_122012                     14619 non-null  bool
 31  Postal Code_122013                     14619 non-null  bool
 32  Postal Code_122014                     14619 non-null  bool
 33  Postal Code_122015                     14619 non-null  bool
 34  Postal Code_122016                     14619 non-null  bool
 35  Postal Code_122017                     14619 non-null  bool
 36  Postal Code_122018                     14619 non-null  bool
 37  Postal Code_122019                     14619 non-null  bool
 38  Postal Code_122020                     14619 non-null  bool
 39  Postal Code_122021                     14619 non-null  bool
 40  Postal Code_122022                     14619 non-null  bool
 41  Postal Code_122023                     14619 non-null  bool
 42  Postal Code_122024                     14619 non-null  bool
 43  Postal Code_122025                     14619 non-null  bool
 44  Postal Code_122026                     14619 non-null  bool
 45  Postal Code_122027                     14619 non-null  bool
 46  Postal Code_122028                     14619 non-null  bool
 47  Postal Code_122029                     14619 non-null  bool
 48  Postal Code_122030                     14619 non-null  bool
 49  Postal Code_122031                     14619 non-null  bool
 50  Postal Code_122032                     14619 non-null  bool
 51  Postal Code_122033                     14619 non-null  bool
 52  Postal Code_122034                     14619 non-null  bool
 53  Postal Code_122035                     14619 non-null  bool
 54  Postal Code_122036                     14619 non-null  bool
 55  Postal Code_122037                     14619 non-null  bool
 56  Postal Code_122038                     14619 non-null  bool
 57  Postal Code_122039                     14619 non-null  bool
 58  Postal Code_122040                     14619 non-null  bool
 59  Postal Code_122041                     14619 non-null  bool
 60  Postal Code_122042                     14619 non-null  bool
 61  Postal Code_122043                     14619 non-null  bool
 62  Postal Code_122044                     14619 non-null  bool
 63  Postal Code_122045                     14619 non-null  bool
 64  Postal Code_122046                     14619 non-null  bool
 65  Postal Code_122047                     14619 non-null  bool
 66  Postal Code_122048                     14619 non-null  bool
 67  Postal Code_122049                     14619 non-null  bool
 68  Postal Code_122050                     14619 non-null  bool
 69  Postal Code_122051                     14619 non-null  bool
 70  Postal Code_122052                     14619 non-null  bool
 71  Postal Code_122053                     14619 non-null  bool
 72  Postal Code_122054                     14619 non-null  bool
 73  Postal Code_122055                     14619 non-null  bool
 74  Postal Code_122056                     14619 non-null  bool
 75  Postal Code_122057                     14619 non-null  bool
 76  Postal Code_122058                     14619 non-null  bool
 77  Postal Code_122059                     14619 non-null  bool
 78  Postal Code_122060                     14619 non-null  bool
 79  Postal Code_122061                     14619 non-null  bool
 80  Postal Code_122062                     14619 non-null  bool
 81  Postal Code_122063                     14619 non-null  bool
 82  Postal Code_122064                     14619 non-null  bool
 83  Postal Code_122065                     14619 non-null  bool
 84  Postal Code_122066                     14619 non-null  bool
 85  Postal Code_122067                     14619 non-null  bool
 86  Postal Code_122068                     14619 non-null  bool
 87  Postal Code_122069                     14619 non-null  bool
 88  Postal Code_122070                     14619 non-null  bool
 89  Postal Code_122071                     14619 non-null  bool
 90  Postal Code_122072                     14619 non-null  bool
dtypes: bool(69), float64(4), int32(2), int64(16)
memory usage: 3.3 MB

,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,Area of the house(excluding basement),...,Postal Code_122063,Postal Code_122064,Postal Code_122065,Postal Code_122066,Postal Code_122067,Postal Code_122068,Postal Code_122069,Postal Code_122070,Postal Code_122071,Postal Code_122072
0,4,2.50,2920,4000,1.5,0,0,5,8,1910,...,False,False,False,False,False,False,False,False,False,False
1,5,2.75,2910,9480,1.5,0,0,3,8,2910,...,False,False,False,False,False,False,False,False,False,False
2,4,2.50,3310,42998,2.0,0,0,3,9,3310,...,False,False,False,False,False,False,False,False,False,False
3,3,2.00,2710,4500,1.5,0,0,4,8,1880,...,False,False,False,False,False,False,False,False,False,False
4,3,2.50,2600,4750,1.0,0,0,4,9,1700,...,False,False,False,False,False,False,False,False,False,False