In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../dataset/dataset.csv')

In [4]:
df = df.drop(["property_url", "id", "address"], axis=1, errors="ignore")

In [5]:
df

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,purpose,city,locality,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
0,2464.0,Apartment,Residential,4.0,3.0,28900000.0,Sale,Dhaka,Dhanmondi,1,2,1,1,3,3,4,Dhaka,Dhanmondi,11728.896104
1,1920.0,Apartment,Residential,3.0,3.0,20000000.0,Sale,Dhaka,Bashundhara R-A,1,1,2,1,3,2,3,Dhaka,Bashundhara R/A,10416.666667
2,1445.0,Apartment,Residential,3.0,3.0,10800000.0,Sale,Dhaka,Banasree,1,2,2,1,1,3,4,Dhaka,Khilgaon,7474.048443
3,1475.0,Apartment,Residential,3.0,3.0,10500000.0,Sale,Dhaka,Uttara,1,2,3,1,3,3,4,Dhaka,Uttara,7118.644068
4,1066.0,Apartment,Residential,2.0,3.0,8000000.0,Sale,Dhaka,Sutrapur,1,1,2,1,4,3,4,Dhaka,Sutrapur,7504.690432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,Apartment,Residential,1.0,1.0,3600000.0,Rent,Dhaka,Bashundhara R.A,1,1,2,3,4,2,13,Dhaka,Bashundhara R/A,9600.000000
18750,375.0,Apartment,Residential,1.0,1.0,3600000.0,Rent,Dhaka,Bashundhara R.A,1,2,1,1,4,2,1,Dhaka,Bashundhara R/A,9600.000000
18751,800.0,Apartment,Residential,2.0,2.0,4800000.0,Rent,Dhaka,Bashundhara R.A,1,1,2,1,3,3,1,Dhaka,Bashundhara R/A,6000.000000
18752,800.0,Apartment,Residential,2.0,2.0,4800000.0,Rent,Dhaka,Bashundhara R.A,1,1,1,1,1,2,1,Dhaka,Bashundhara R/A,6000.000000
18753,1600.0,Office,Commercial,3.0,3.0,2850000.0,Rent,Dhaka,Adabor,1,2,2,1,1,2,1,Dhaka,Mohammadpur,1781.250000

In [6]:
df["area"] = pd.to_numeric(df["area"], errors="coerce")
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["price_per_sqft"] = pd.to_numeric(df["price_per_sqft"], errors="coerce")

In [7]:
df

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,purpose,city,locality,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
0,2464.0,Apartment,Residential,4.0,3.0,28900000.0,Sale,Dhaka,Dhanmondi,1,2,1,1,3,3,4,Dhaka,Dhanmondi,11728.896104
1,1920.0,Apartment,Residential,3.0,3.0,20000000.0,Sale,Dhaka,Bashundhara R-A,1,1,2,1,3,2,3,Dhaka,Bashundhara R/A,10416.666667
2,1445.0,Apartment,Residential,3.0,3.0,10800000.0,Sale,Dhaka,Banasree,1,2,2,1,1,3,4,Dhaka,Khilgaon,7474.048443
3,1475.0,Apartment,Residential,3.0,3.0,10500000.0,Sale,Dhaka,Uttara,1,2,3,1,3,3,4,Dhaka,Uttara,7118.644068
4,1066.0,Apartment,Residential,2.0,3.0,8000000.0,Sale,Dhaka,Sutrapur,1,1,2,1,4,3,4,Dhaka,Sutrapur,7504.690432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,Apartment,Residential,1.0,1.0,3600000.0,Rent,Dhaka,Bashundhara R.A,1,1,2,3,4,2,13,Dhaka,Bashundhara R/A,9600.000000
18750,375.0,Apartment,Residential,1.0,1.0,3600000.0,Rent,Dhaka,Bashundhara R.A,1,2,1,1,4,2,1,Dhaka,Bashundhara R/A,9600.000000
18751,800.0,Apartment,Residential,2.0,2.0,4800000.0,Rent,Dhaka,Bashundhara R.A,1,1,2,1,3,3,1,Dhaka,Bashundhara R/A,6000.000000
18752,800.0,Apartment,Residential,2.0,2.0,4800000.0,Rent,Dhaka,Bashundhara R.A,1,1,1,1,1,2,1,Dhaka,Bashundhara R/A,6000.000000
18753,1600.0,Office,Commercial,3.0,3.0,2850000.0,Rent,Dhaka,Adabor,1,2,2,1,1,2,1,Dhaka,Mohammadpur,1781.250000

In [10]:
numeric_cols = df.select_dtypes(include=["number"]).columns
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [11]:
numeric_cols

Index(['area', 'num_bath_rooms', 'num_bed_rooms', 'price',
       'relaxation_amenity_count', 'security_amenity_count',
       'maintenance_or_cleaning_amenity_count', 'social_amenity_count',
       'expendable_amenity_count', 'service_staff_amenity_count',
       'unclassify_amenity_count', 'price_per_sqft'],
      dtype='str')

In [12]:
categorical_cols = df.select_dtypes(include=["object", "string"]).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [13]:
categorical_cols

Index(['building_type', 'building_nature', 'purpose', 'city', 'locality',
       'division', 'zone'],
      dtype='str')

In [14]:
df = pd.get_dummies(
    df,
    columns=["building_type", "building_nature", "purpose", "city", "locality", "division", "zone"],
    drop_first=True,
    dtype=int
)

In [15]:
df

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,...,zone_Sub-district of Sherpur,zone_Sub-district of Sirajganj,zone_Sub-district of Tangail,zone_Sub-district of Thakurgaon,zone_Sutrapur,zone_Sylhet City,zone_Tejgaon,zone_Turag,zone_Unknown,zone_Uttara
0,2464.0,4.0,3.0,28900000.0,1,2,1,1,3,3,...,0,0,0,0,0,0,0,0,0,0
1,1920.0,3.0,3.0,20000000.0,1,1,2,1,3,2,...,0,0,0,0,0,0,0,0,0,0
2,1445.0,3.0,3.0,10800000.0,1,2,2,1,1,3,...,0,0,0,0,0,0,0,0,0,0
3,1475.0,3.0,3.0,10500000.0,1,2,3,1,3,3,...,0,0,0,0,0,0,0,0,0,1
4,1066.0,2.0,3.0,8000000.0,1,1,2,1,4,3,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,1.0,1.0,3600000.0,1,1,2,3,4,2,...,0,0,0,0,0,0,0,0,0,0
18750,375.0,1.0,1.0,3600000.0,1,2,1,1,4,2,...,0,0,0,0,0,0,0,0,0,0
18751,800.0,2.0,2.0,4800000.0,1,1,2,1,3,3,...,0,0,0,0,0,0,0,0,0,0
18752,800.0,2.0,2.0,4800000.0,1,1,1,1,1,2,...,0,0,0,0,0,0,0,0,0,0
18753,1600.0,3.0,3.0,2850000.0,1,2,2,1,1,2,...,0,0,0,0,0,0,0,0,0,0

In [16]:
Q1 = df["area"].quantile(0.25)
Q3 = df["area"].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[(df["area"] >= lower_limit) & (df["area"] <= upper_limit)]

In [17]:
df

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,...,zone_Sub-district of Sherpur,zone_Sub-district of Sirajganj,zone_Sub-district of Tangail,zone_Sub-district of Thakurgaon,zone_Sutrapur,zone_Sylhet City,zone_Tejgaon,zone_Turag,zone_Unknown,zone_Uttara
0,2464.0,4.0,3.0,28900000.0,1,2,1,1,3,3,...,0,0,0,0,0,0,0,0,0,0
1,1920.0,3.0,3.0,20000000.0,1,1,2,1,3,2,...,0,0,0,0,0,0,0,0,0,0
2,1445.0,3.0,3.0,10800000.0,1,2,2,1,1,3,...,0,0,0,0,0,0,0,0,0,0
3,1475.0,3.0,3.0,10500000.0,1,2,3,1,3,3,...,0,0,0,0,0,0,0,0,0,1
4,1066.0,2.0,3.0,8000000.0,1,1,2,1,4,3,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,1.0,1.0,3600000.0,1,1,2,3,4,2,...,0,0,0,0,0,0,0,0,0,0
18750,375.0,1.0,1.0,3600000.0,1,2,1,1,4,2,...,0,0,0,0,0,0,0,0,0,0
18751,800.0,2.0,2.0,4800000.0,1,1,2,1,3,3,...,0,0,0,0,0,0,0,0,0,0
18752,800.0,2.0,2.0,4800000.0,1,1,1,1,1,2,...,0,0,0,0,0,0,0,0,0,0
18753,1600.0,3.0,3.0,2850000.0,1,2,2,1,1,2,...,0,0,0,0,0,0,0,0,0,0

In [18]:
Q1 = df["price_per_sqft"].quantile(0.25)
Q3 = df["price_per_sqft"].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[(df["price_per_sqft"] >= lower_limit) & 
        (df["price_per_sqft"] <= upper_limit)]

In [19]:
df

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,...,zone_Sub-district of Sherpur,zone_Sub-district of Sirajganj,zone_Sub-district of Tangail,zone_Sub-district of Thakurgaon,zone_Sutrapur,zone_Sylhet City,zone_Tejgaon,zone_Turag,zone_Unknown,zone_Uttara
0,2464.0,4.0,3.0,28900000.0,1,2,1,1,3,3,...,0,0,0,0,0,0,0,0,0,0
1,1920.0,3.0,3.0,20000000.0,1,1,2,1,3,2,...,0,0,0,0,0,0,0,0,0,0
2,1445.0,3.0,3.0,10800000.0,1,2,2,1,1,3,...,0,0,0,0,0,0,0,0,0,0
3,1475.0,3.0,3.0,10500000.0,1,2,3,1,3,3,...,0,0,0,0,0,0,0,0,0,1
4,1066.0,2.0,3.0,8000000.0,1,1,2,1,4,3,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,1.0,1.0,3600000.0,1,1,2,3,4,2,...,0,0,0,0,0,0,0,0,0,0
18750,375.0,1.0,1.0,3600000.0,1,2,1,1,4,2,...,0,0,0,0,0,0,0,0,0,0
18751,800.0,2.0,2.0,4800000.0,1,1,2,1,3,3,...,0,0,0,0,0,0,0,0,0,0
18752,800.0,2.0,2.0,4800000.0,1,1,1,1,1,2,...,0,0,0,0,0,0,0,0,0,0
18753,1600.0,3.0,3.0,2850000.0,1,2,2,1,1,2,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df = df[df["num_bath_rooms"] <= df["num_bed_rooms"] + 2]

In [21]:
df

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,...,zone_Sub-district of Sherpur,zone_Sub-district of Sirajganj,zone_Sub-district of Tangail,zone_Sub-district of Thakurgaon,zone_Sutrapur,zone_Sylhet City,zone_Tejgaon,zone_Turag,zone_Unknown,zone_Uttara
0,2464.0,4.0,3.0,28900000.0,1,2,1,1,3,3,...,0,0,0,0,0,0,0,0,0,0
1,1920.0,3.0,3.0,20000000.0,1,1,2,1,3,2,...,0,0,0,0,0,0,0,0,0,0
2,1445.0,3.0,3.0,10800000.0,1,2,2,1,1,3,...,0,0,0,0,0,0,0,0,0,0
3,1475.0,3.0,3.0,10500000.0,1,2,3,1,3,3,...,0,0,0,0,0,0,0,0,0,1
4,1066.0,2.0,3.0,8000000.0,1,1,2,1,4,3,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18749,375.0,1.0,1.0,3600000.0,1,1,2,3,4,2,...,0,0,0,0,0,0,0,0,0,0
18750,375.0,1.0,1.0,3600000.0,1,2,1,1,4,2,...,0,0,0,0,0,0,0,0,0,0
18751,800.0,2.0,2.0,4800000.0,1,1,2,1,3,3,...,0,0,0,0,0,0,0,0,0,0
18752,800.0,2.0,2.0,4800000.0,1,1,1,1,1,2,...,0,0,0,0,0,0,0,0,0,0
18753,1600.0,3.0,3.0,2850000.0,1,2,2,1,1,2,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df = df.drop("price_per_sqft", axis=1)

In [23]:
print(df.info())
print("Final Shape:", df.shape)

<class 'pandas.DataFrame'>
Index: 17916 entries, 0 to 18753
Columns: 316 entries, area to zone_Uttara
dtypes: float64(4), int64(312)
memory usage: 43.3 MB
None
Final Shape: (17916, 316)